### ISSUE TITLE
logical contradictions in profile owned nft

### ISSUE THREAD

**Issue by N3koSempai** [LiberMall/.github#2]
### Bug Type

UX

### Reproduction steps

1 - connect a clean wallet
2 - go to the profile
3 - in the property section

### Actual result

When you don't have any nft yet, the owned section is shown empty.
However the load next button is displayed to view other tabs. It is unnecessary because all tabs by logic will be empty.

### Expected result

The next load next should be disabled if you still do not exceed the nfts space for that tab.

### Suggested Severity

Low

### Device

Desktop 
- OS: Linux
- Browser: chromiun like

**Comment by AntonMeep** [comment]
All tabs will remain, in case some of the tabs are empty, an appropriate message will be displayed.
