### ISSUE TITLE
Social media icons are not displayed

### ISSUE THREAD

**Issue by Lana4cool** [LiberMall/.github#5]
### Bug Type

UI

### Reproduction steps

1. Scroll the page to the footer
2. See the issue in the social media section

### Actual result

Social media icons are not displayed

### Expected result

Is expected to see the social media icons.

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):
    OS: Windows 10
    Browser: Firefox
    Version: 105.0.3

Smartphone (please complete the following information):
    Device: OUKITEL
    OS: Android
    Browser Chrome
    Version: 106.0.5249.79

### Additional Context

![изображение](https://user-images.githubusercontent.com/109892803/195087859-ab071069-f399-4f8b-860a-9edfcca29cb9.png)
![изображение](https://user-images.githubusercontent.com/109892803/195087877-186d719c-30ea-4721-afa6-04451d781670.png)

**Comment by AntonMeep** [comment]
Temporary issue with icon distribution, has been fixed.
