### ISSUE TITLE
Error display "TON Dimonds" collection

### ISSUE THREAD

**Issue by Andar9Bahar** [LiberMall/.github#9]
### Bug Type

Functional

### Reproduction steps

When switching to the "TON Dimonds" collection
![image](https://user-images.githubusercontent.com/101738014/195691850-84ef599e-8e69-4f2d-8faa-0ca34fa2397e.png)

### Actual result

This leads to an error, although other collections open without problems
![image](https://user-images.githubusercontent.com/101738014/195692461-46aa1d38-e367-4d5f-87bc-58af99295870.png)

### Expected result

Go to the "TON Diamonds" collection page

### Suggested Severity

Medium

### Device

- OS: Windows8.1
- Browser: Yandex and Google 
- Version: Yandex(104.0.5112.891), Google(106.0.5249.119 )

**Comment by AntonMeep** [comment]
Seems to be a temporary issue with the backend, fixed itself a while back.
